# Site settings
title: Brooks Consulting LLC
email: jeffl@brooksconsulting-llc.com
description: Brooks Consulting LLC provides ISP consulting services to the world's largest providers.
baseurl: "brooksconsulting-llc.com"
url: "brooksconsulting-llc.com"

# Build settings
markdown: kramdown
permalink: pretty
